package day4;
class Resource{
	
}
class Abc{
	public void run() {
		int x=0;
		int y=10;
		int z=y/x;
		System.out.println(z);
	}
}

public class MyExcept {

	public static void main(String[] args) {
		try {
			new Abc().run();
		}
		catch(ArithmeticException e) {
			System.out.println(e.getMessage());
		}
		finally {
			System.out.println("Finally block");
		}
		
//		new Abc().run();
		System.out.println("This is the prog continuation..");
	}

}
